### ISSUE TITLE
Weekly validation presentation

### ISSUE THREAD

**Issue by rikvl** [chime-experiment/Daily_validation#3]
The weekly validation notebook works really well! From the first impression, I have a few small points regarding presentation:

- I think it would be good to have a label for the color axis, even if it would be something not very meaningful like "something something power (arbitrary units)". The unlabeled colorbar left me wondering.

- Related, in the grid view, it would be good if the label for the horizontal axes ("NS baseline") would appear just below the axes it refers to, but _above_ the colorbar.

- In the grid view, would it maybe make sense to add a tiny title/text to each panel stating the CSD? I suppose this view is intended for seeing trends rather than for checking individual days, but a CSD for each panel may still be useful to quickly identify days.

- The plot titles refer to LSDs, while the input argument and the Markdown is in CSDs. Was there some subtle difference between the two, or are they exactly the same (as long as "local" is the CHIME telescope)?

- I tried out some different values of `num_days`. When that variable is a multiple of 3, the grid view creates a superfluous row. E.g., for `num_days = 6`, I get a 3x3 grid of panels, rather than 2 rows of 3 panels each.

- Related, not sure if this is worth the effort, but it may be nice to remove any superfluous panels in the grid view. I.e., for `num_days = 14`, the grid view creates 5x3 = 15 panels. Maybe you can remove the 15th panel and just have an empty space in the figure there, rather than an empty panel that looks just like a day for which there is no data.

- I guess this reflects my lack of understanding of how the pipeline and surrounding infrastructure is set up, but I got confused by the message "No data available for CSD ...". Does this mean that there is currently no pipeline data product available, or that there never will be raw data available for that day? If the former, is there an easy way to distinguish between days for which there is _currently_ no data available vs. days for which there will _never_ be data available? If so, it may be nice to indicate that both in the list and grid view, if you think that's useful.

**Comment by ljgray** [comment]
Thanks for the feedback, I should be able to address all of these.

As far the the CSD/LSD labeling goes, they're basically being used interchangeably here, but I will adjust that to make sure it's actually consistent
